### ISSUE TITLE
Don't use UFW Reset

### ISSUE THREAD

**Issue by jamescun** [chef-cookbooks/ufw#11]
I noticed that during the chef run for this cookbook, it executes `ufw --force reset` (in default.rb) forcing UFW to drop all rules and disable the firewall. It then immediately enables the firewall again and re-adds firewall rules.

I can see why the cookbook does this, it is an easy way of reconciling differences between the cookbooks rules and the currently applied rules.

However for us this is causing timeouts on our network between resetting the firewall and adding the rules again (0.5-2 seconds). Is there a workaround or an option to disable this reset (with the downside of not removing old rules)?

**Comment by iennae** [comment]
As of version 3.0.0 of this cookbook this has been removed from the default recipe.
