### ISSUE TITLE
chef-solo node.json ignored

### ISSUE THREAD

**Issue by nerdyglasses** [chef-cookbooks/ufw#13]
Hi,

I'm using this node config. I want to allow app servers to connect to e.g. mongodb.
Unfortunately this config is ignored completely I even tried simple things like
`{ "http": { "port": "80" }}`

``` json
{
  "automatic": {
    "ipaddress": "10.0.0.1"
  },
  "run_list": [
    "role[server]",
    "role[redis]",
    "role[mongodb]",
    "role[memcached]",
    "role[elasticsearch]"
  ],
  "default_attributes": {
  },
  "override_attributes": {
    "firewall": {
      "rules": [
        { "mongodb from 10.0.0.2": { "source": "10.0.0.2", "port": "27017" }}
      ]
    }
  }
}
```

I have no other config in roles or anywhere else.
I only run the "ufw" recipe.

Any idea why this config doesn't work?

**Comment by tas50** [comment]
I'm going to close this out, but please open it back up if you're still having this issue with chef local mode.
