### ISSUE TITLE
firewall dependency is too liberal

### ISSUE THREAD

**Issue by icberg7** [chef-cookbooks/ufw#16]
I recently updated the berksfile on an upstream cookbook that depends on `ufw` and I received this error:
```
       ================================================================================
       Recipe Compile Error in /tmp/kitchen/cache/cookbooks/firewall/libraries/resource_firewall.rb
       ================================================================================
       
       SyntaxError
       -----------
       /tmp/kitchen/cache/cookbooks/poise/files/halite_gem/poise/helpers/option_collector.rb:89: syntax error, unexpected tLABEL
        def option_collector_attribute(name, default: {}, parser: nil)
                                                     ^
       /tmp/kitchen/cache/cookbooks/poise/files/halite_gem/poise/helpers/option_collector.rb:131: syntax error, unexpected keyword_end, expecting $end

```

This cookbook depends on the `firewall` cookbook, which depends on `poise`. Based on the notes by @coderanger https://github.com/poise/poise/issues/12#issuecomment-113586185, the `poise` cookbook is not compatible with Chef 11.

I believe this cookbook should depend on `firewall` via a pessimistic version constraint, such as:
```
depends 'firewall', ~> 0.11.8
```

This would avoid the poise dependency.

**Comment by tb3088** [comment]
actually I believe '~>0.9' is sufficient. We just need to stay clear of 1.0+

**Comment by wojnosystems** [comment]
I'm also experiencing this for new nodes.

Possible workaround:
It seems as though I can compel it to use 0.11.8 by explicitly requiring that version for firewall in my metadata.rb as @icberg7 suggested.

**Comment by coderanger** [comment]
You can set version restrictions in your environment or in your wrapper cookbook. Poise 1.x supported Chef 11 and should probably still work, though overall most community cookbooks don't specifically support 11 anymore.

**Comment by tb3088** [comment]
if community cookbooks are going to deprecate support for very much in use Chef versions that needs to be explicitly highlighted. A properly written cookbook does not depend on Chef version peculiarities unless there's a damn good reason.

I don't know how to munge a metadata file to have dependencies specified on major Chef versions.
