### ISSUE TITLE
ufw becomes inactive when chef is run more than once with no changes to the ufw rules

### ISSUE THREAD

**Issue by DanNeish** [chef-cookbooks/ufw#23]
### Cookbook version

1.0.0
### Chef-client version

12.13.30
### Platform Details

Ubuntu 14.04.5 LTS (GNU/Linux 4.4.0-34-generic x86_64)
Digital Ocean Droplet
### Scenario:

Running Chef two or more times results in UFW being disabled. Occurs if there are no changes to the configuration for ufw i.e. no changes to the rules for a node. Adding/removing/changing a ufw rule in the node configuration and then running chef results in the firewall becoming active again.
I am running chef using the following command:
bundle exec knife solo bootstrap root@SERVERIP
### Steps to Reproduce:

Provision with Chef Solo with the following recipes:
   recipe[firewall::default]
   recipe[ufw::default](firewall:default was required to resolve https://github.com/chef-cookbooks/ufw/issues/20)
After successful completion, run chef again. (Do not make any changes to the configuration for ufw)
### Expected Result:

ufw status should be active
### Actual Result:

ufw inactive

Relevant Cookbook Versions:
ufw 1.0.0
firewall 2.5.2
iptables 2.2.0

Gem Versions being used:
gem 'knife-solo', '0.6.0'
gem 'chef', '12.13.30'
gem 'chef-zero', '4.9.0'
gem 'berkshelf', '4.3.5'

UFW version:
ufw 0.34~rc-0ubuntu2

**Comment by corporealfunk** [comment]
I'm seeing this same behavior, though briefly looking through the code, I think it has more to do with how the firewall_rule resource actually applies rules. My guess is that it sees "nothing has changed" and therefore doesn't apply the rule. Given that this ufw cookbook clears all rules and disables the firewall at the start of the recipe, the "same old rules" simply aren't reloaded again.

**Comment by ziazek** [comment]
I solved it by removing ufw from the run_list and using the firewall cookbook directly.

**Comment by DanNeish** [comment]
@ziazek could you share a snippet of where you specified rules in your node/role definition? I'm having trouble specifying firewall rules using the firewall cookbook directly.

**Comment by ziazek** [comment]
@DanNeish I created a new cookbook: site-cookbooks/firewall-zz/recipes/default.rb,

```ruby
# https://github.com/chef-cookbooks/firewall

firewall 'default' do
  ipv6_enabled node['firewall']['ipv6_enabled']
  action :install
end

firewall_rule 'allow world to ssh' do
  port 22
  source '0.0.0.0/0'
  only_if { linux? && node['firewall']['allow_ssh'] }
end

firewall_rule 'http/https' do
  protocol :tcp
  port     [80, 443]
  command   :allow
end
```

Then, in roles/server.json, edit the **run_list**:

```json
"run_list": [
    // ...
    // install and enable ufw
    "recipe[firewall::default]",
    // "recipe[ufw::default]", // disabled
    "recipe[firewall-zz::default]"
  // ...
]
```

Hope this helps.

**Comment by iennae** [comment]
@DanNeish With the changes in the default recipe with version 3.0.0 this doesn't appear to be a problem anymore. Thanks for reporting the issue.

**Comment by alepore** [comment]
With ufw 3.1.0, on Ubuntu 16:04 i'm still getting:

    $ sudo ufw status
    Status: inactive

I'm now using manual `firewall_rule` rules and all works as expected.
