### ISSUE TITLE
['firewall']['rules'] support hash of rules

### ISSUE THREAD

**Issue by atheiman** [chef-cookbooks/ufw#33]
`['firewall']['rules']` being an array does not allow the attribute to be merge at various precedences. for example, if a cookbook wants to add a rule as an attribute at `default` level, and an environment wants to add a different rule at `override` level. This would result in only the environment's override rule being set.

Consider the following data structures:

```ruby
{
  'firewall' => {
    'rules' => [
      { 'http'  => { 'port' => '80'  } },
      { 'https' => { 'port' => '443' } }
    ]
  }
}

{
  'firewall' => {
    'rules' => {
      'http'  => { 'port' => '80'  },
      'https' => { 'port' => '443' }
    }
  }
}
```

I think the second (hash) form makes more sense for this, and it allows the merging of attributes at different precedence levels.

Support for rules defined as a hash should be added. It can be added in a backwards compatible way too, the code can check for `['firewall']['rules']` being an `Array` and use the current logic, or if its a `Hash` use the new logic I am suggesting.

edit: Ive added pull request #34 showing this in code

**Comment by gerard-leijdekkers** [comment]
Exactly what I needed. Thanks!
